export const NALU_TYPES = {
  UNSPECIFIED: 0,
  CODED_SLICE_NON_IDR: 1,
  CODED_SLICE_DATA_PARTITION_A: 2,
  CODED_SLICE_DATA_PARTITION_B: 3,
  CODED_SLICE_DATA_PARTITION_C: 4,
  CODED_SLICE_IDR: 5,
  SEI: 6,
  SPS: 7,
  PPS: 8,
  AUD: 9,
  END_OF_SEQUENCE: 10,
  END_OF_STREAM: 11,
  FILLER: 12,
  SPS_EXT: 13,
  PREFIX_NAL: 14,
  SUBSET_SPS: 15,
  DPS: 16,
  // 17..18 reserved
  CODED_SLICE_AUX: 19,
  CODED_SLICE_SVC_EXTENSION: 20,
  // 20..23 reserved
  // 24..31 unspecified
};

export const SEI_PAYLOAD_TYPES = {
  BUFFERING_PERIOD: 0,
  PIC_TIMING: 1,
  PAN_SCAN_RECT: 2,
  FILLER_PAYLOAD: 3,
  USER_DATA_REGISTERED_ITU_T_T35: 4,
  USER_DATA_UNREGISTERED: 5,
  RECOVERY_POINT: 6,
  DEC_REF_PIC_MARKING_REPETITION: 7,
  SPARE_PIC: 8,
  SCENE_INFO: 9,
  SUB_SEQ_INFO: 10,
  SUB_SEQ_LAYER_CHARACTERISTICS: 11,
  SUB_SEQ_CHARACTERISTICS: 12,
  FULL_FRAME_FREEZE: 13,
  FULL_FRAME_FREEZE_RELEASE: 14,
  FULL_FRAME_SNAPSHOT: 15,
  PROGRESSIVE_REFINEMENT_SEGMENT_START: 16,
  PROGRESSIVE_REFINEMENT_SEGMENT_END: 17,
  MOTION_CONSTRAINED_SLICE_GROUP_SET: 18,
  FILM_GRAIN_CHARACTERISTICS: 19,
  DEBLOCKING_FILTER_DISPLAY_PREFERENCE: 20,
  STEREO_VIDEO_INFO: 21,
  SCALABILITY_INFO: 24,
};

export const SAR = {
  EXTENDED: 255,
};
